# Programmation Orientée Objets (POO - OOP)

1 objet python peut représenter:
- 1 objet de la vie réelle
- 1 être vivant
- 1 concept, 1 idée
- etc.

1 objet va avoir des caractéristiques (i.e. attributs, propriétés, champs). 
Exemple: 1 objet personne avec 3 attributs: 1 nom, 1 prénom, 1 âge

1 objet va être crée à partir d'un modèle = 1 classe.
Exemple: classe Personne => n objets à partir de cette classe

In [102]:
import numpy as np
import pandas as pd

# du module datetime, on prend les types (classes) date et datetime
from datetime import date, datetime

In [19]:
np.__version__

'1.26.4'

In [95]:
pd.__version__

'2.2.2'

## Création des objets

In [7]:
# création d'un objet numpy de la classe 'ndarray'
x = np.linspace(0, 6*np.pi, 10_000)
x

array([0.00000000e+00, 1.88514411e-03, 3.77028821e-03, ...,
       1.88457856e+01, 1.88476708e+01, 1.88495559e+01])

In [9]:
# classe ndarray = N Dimensional Array (1D, 2D, 3D, ...)
type(x)

numpy.ndarray

In [13]:
# 2e objet de la classe ndarray
data = np.random.normal(10, 3.5, 1_000_000)
data

array([18.45947628, 10.05585473, 10.3507499 , ..., 18.80482688,
       10.49200502, 10.27011442])

## attributs/propriétés

In [17]:
# caractéristiques (attributs ou propriétés)
print('x shape:', x.shape)
print('data shape:', data.shape)

x shape: (10000,)
data shape: (1000000,)


In [21]:
data.dtype

dtype('float64')

In [25]:
# uint8 : entier qui va de 0 à 255
image = np.zeros((4, 4), dtype='uint8')
image

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [27]:
image.shape

(4, 4)

In [31]:
data.shape = (1000, 1000)
data.shape

(1000, 1000)

In [35]:
# data.shape = (3, 4)
# ValueError: cannot reshape array of size 1000000 into shape (3,4)

In [37]:
image.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [39]:
print(x[0])
print(x[-1])
print(x[:3])
print(x[-3:])
print(x[::1000])

0.0
18.84955592153876
[0.         0.00188514 0.00377029]
[18.84578563 18.84767078 18.84955592]
[ 0.          1.88514411  3.77028821  5.65543232  7.54057643  9.42572053
 11.31086464 13.19600875 15.08115285 16.96629696]


In [51]:
# ligne n°0
data[0]

array([18.45947628, 10.05585473, 10.3507499 ,  8.85588383,  7.7019947 ,
       10.54847478,  8.00958298, 15.50725736,  5.19608704,  7.97268968,
        6.76906011, 12.54248986,  7.36358289, 15.03578036,  6.30676537,
       13.60862642, 10.84742004, 15.29395914, 10.1025512 ,  8.9235263 ,
       13.28977459, 12.70451078,  9.80748265, 17.27912626,  8.45698227,
        6.92516157, 16.29427329, 11.24721921, 11.94234319,  9.37902483,
       15.64247246, 12.09437016,  2.8297312 , 10.41683861, 14.45556422,
        6.6907664 , 12.79865523,  8.97020188, 11.88722729,  7.34115741,
       10.89496988, 12.55595596, 14.2860187 , 12.06229506,  8.53681669,
        7.39699861,  7.37815458,  6.00043365, 14.41679025,  9.5808497 ,
        6.18319407,  8.01200049, 11.04440257, 12.36518849, 11.87613342,
       11.89169846,  7.55956786, 10.47936562,  7.8641295 , 10.69999615,
       11.41162703,  6.31932978,  7.59686001,  9.86510855, 11.26939021,
       13.08686698,  5.98128975, 10.87852317, 14.70818969, 14.24

In [47]:
# data au tuple d'indices 0, 0 (ligne, colonne) 
data[0, 0]

18.459476275034447

In [49]:
# 5 premières lignes, 5 premières colonnes
data[:5, :5]

array([[18.45947628, 10.05585473, 10.3507499 ,  8.85588383,  7.7019947 ],
       [15.92310554,  7.31211343, 12.57049345, 11.51449513,  8.83832103],
       [15.77726536, 13.20773949,  9.83579729,  6.82271855, 15.13071626],
       [14.95077833, 15.81454837, 16.99010471, 10.78644043, 11.78919569],
       [ 6.43956568,  9.78203598,  1.49815842, 14.67930676, 19.06481915]])

In [53]:
# colonne n°4
data[:, 4]

array([ 7.7019947 ,  8.83832103, 15.13071626, 11.78919569, 19.06481915,
        9.29988602,  6.95799249,  7.84723016,  9.90362152,  7.49533062,
        8.944669  , 12.62276117,  3.15164976, 10.78894522, 10.95749153,
       13.70257071,  5.27205899,  9.96875133,  7.57090622,  9.28200689,
        6.88952155,  7.16492306, 13.88822882,  3.74886958, 19.57228677,
       16.65722184, 13.46399335, 15.49190266, 11.05849773, 13.01785198,
        5.85669077, 12.1938713 , 12.59183483, 12.24019365, 12.69929303,
        5.56986923, 11.58603786,  5.05666635, 11.07700562, 12.13584858,
        5.79514874,  8.26421164, 13.01107889, 11.33146568, 13.76750365,
        5.82071548, 16.6399748 ,  7.42384628,  5.79657609, 13.52312955,
       10.29583993, 10.89747113, 10.93991743,  9.3874765 ,  6.23269705,
        5.40118766, 12.76076633,  8.52256377, 16.00090901,  5.51227114,
        7.64943664,  7.81056253,  4.37243558,  6.84598262,  5.94535738,
       13.59328357, 10.9500027 ,  8.17887352,  6.37346741, 11.64

## Méthodes

### méthodes ndarray

In [58]:
print(data.mean())
print(data.std())

10.004734123487456
3.506432088514374


In [76]:
data.diagonal()

array([18.45947628,  7.31211343,  9.83579729, 10.78644043, 19.06481915,
        8.1031377 , 12.84308338,  3.00546509, 10.03004604, 13.60817153,
        8.27952321,  7.35390661,  9.18435334,  6.73925908, 11.79021836,
       10.640599  , 15.22247532,  4.23480792,  9.40347114, 15.2069308 ,
       15.70483491, 13.68748695, 14.54368829, 10.32418639, 13.26723419,
       12.01213001, 11.14524197,  9.09726299, 13.89437318, 11.92503722,
       16.88101316, 16.81302738,  8.15578951, 16.12993736, 11.81090431,
       10.92108911, 15.71685186, 17.47015433,  9.89053434,  4.65281997,
       10.46628232, 10.6887066 ,  8.02751619, 11.77940215, 11.53411126,
        5.83580838, 12.42468934,  9.74577203,  6.12073464, 10.98808652,
        5.48315989,  5.79443648,  5.6304143 , 10.64755314, 12.57579899,
       15.87037029, 11.28176757, 10.87875437, 12.0992097 , 10.92415306,
       10.35761308, 10.94318962, 11.52339258, 12.31277836,  8.0205253 ,
       11.24608481,  7.01158521,  9.17008395,  8.98726215, 12.13

### méthodes du type str

In [81]:
ville = 'Montpellier'

In [83]:
ville.upper()

'MONTPELLIER'

In [85]:
ville.index('l')

6

In [89]:
ville.count('l')

2

In [91]:
len(ville)

11

## Exemple: données temporelles